apiVersion: v1
kind: Pod
metadata:
  name: pt-jet-class-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/jmduarte/pytorch-jet-classify:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 4Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 2Gi
        cpu: "1"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /ptjetclassvol
      name: pt-jet-class-vol
  restartPolicy: Never
  volumes:
    - name: pt-jet-class-vol
      persistentVolumeClaim:
        claimName: pt-jet-class-vol
