apiVersion: batch/v1
kind: Job
metadata:
  name: pt-jet-bo-job-$PRECb
  labels:
    jobgroup: pt-jet-bo-job
spec:
  template:
    spec:
      containers:
      - name: jet-bayesian-optimize
        image:  gitlab-registry.nautilus.optiputer.net/jmduarte/pytorch-jet-classify:latest
        terminationMessagePolicy: FallbackToLogsOnError
        command:
        - "python"
        args:
        - /opt/repo/pytorch-jet-classify/jet_optimize.py
        - -i
        - /ptjetclassvol/rand_train_data/0/
        - -t
        - /ptjetclassvol/train_data/test/
        - -c
        - /opt/repo/pytorch-jet-classify/configs/train_config_threelayer.yml
        - -e
        - "250"
        - -o
        - /ptjetclassvol/BO_output/
        - -b
        - "$PREC"
        volumeMounts:
        - mountPath: /ptjetclassvol
          name: pt-jet-class-vol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            memory: 2Gi
            cpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/ben-hawks/pytorch-jet-classify
          - -b
          - master
          - /opt/repo/pytorch-jet-classify
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: pt-jet-class-vol
        persistentVolumeClaim:
          claimName: pt-jet-class-vol
      restartPolicy: Never
  backoffLimit: 5